version: 2
jobs:
  build:
    docker:
      - image: ftynse/islutils:build
    steps:
      - checkout
      - run:
          name: checkout isl
          command: git submodule update --init --recursive external/isl
      - run:
          name: checkout pet
          command: git submodule update --init external/pet
      - run: mkdir -p build
      - run:
          name: cmake
          command: (cd build; cmake ..)
      - run:
          name: build isl
          command: (cd build; make isl)
      - run:
          name: build pet
          command: (cd build; make pet)
      - run:
          name: build
          command: (cd build; make)
      - run:
          name: test
          command: (cd build; make check)
